### ISSUE TITLE
Crashes with some errors

### ISSUE THREAD

**Issue by Axelr** [cyrale/gulpfile.js#1]
Doesn't display error and blocks on "sass:public:nest".

Happens to me when i typed variable name that doesn't exists.

Bisou

**Comment by cyrale** [comment]
Test v3.0.0. More errors will be displayed by this version.

**Comment by Axelr** [comment]
Now i see the error about the undefined variable, but i still have to stop and start again to make it run.

**Comment by cyrale** [comment]
Can you send a sample code and the error message? I will try to reproduce and correct this error.

**Comment by cyrale** [comment]
I tried with different configurations and everything seems to work properly. Do you have a concrete example? Which version of node do you use?
